apiVersion: v1
kind: Pod
metadata:
  name: pod-challenge02
  labels:
    app: nginx
    service: web
spec:
  containers:
    - image: roxsross12/k8s_test_web:latest
      name: container
      imagePullPolicy: Always