apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      tier: database
  template:
    metadata:
      labels:
        app: mongo
        tier: database
    spec:
      containers:
        - name: mongo
          image: mongo:3.0-wheezy
          ports:
            - name: mongo
              containerPort: 27017