apiVersion: v1
kind: Service
metadata:
  name: letschat
  labels:
    app: letschat
    tier: backend
spec:
  type: NodePort
  ports: 
    - name: http
      port: 8080
      targetPort: http-server
  selector:
    app: letschat
    tier: backend