apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deploy
  labels:
    app: consumer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: contenedor-consumer
          image: roxsross12/consumer:1.0.0
          env:
            - name: PYTHONUNBUFFERED
              value: "1"