apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ch05
  labels:
    app: app-ch05
spec:
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: app-ch05
  template:
    metadata:
      labels:
        app: app-ch05
    spec:
      containers:
        - image: roxsross12/k8s_test_web:latest
          name: contenedor-ch05
          ports:
            - name: http
              containerPort: 80
    