apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-ch04
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-ch04
  template:
    metadata:
      labels:
        app: pod-ch04
    spec:
      containers:
        - image: roxsross12/k8s_test_web:latest
          name: contenedor-ch04